# Assignment 1

The goal of this assignment is to start working with PyTorch.


## Preparation Steps

In [9]:
# Import all necessary python packages
import numpy as np
import torch



In [10]:
%config Completer.use_jedi = False #(fix auto complete)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Config option `use_jedi` not recognized by `IPCompleter`.
  """Entry point for launching an IPython kernel.


## <font color = 'blue'> Question 1. Basic Operations with Tensors </font>

Your taks for this question is to follow the NumPy  [**tutorial**](https://jalammar.github.io/visual-numpy/?fbclid=IwAR0tSntx5mj1aHteokRKrT4G6z77M3z0Quj40AQZ9mvKlhs2RTN3xXrc6Eo) we covered in the lecture, and 'mirror' each of the operations presented in the tutorial with tensors in PyTorch. 

You may find useful to consult this PyTorch introductory [tutorial](https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/), and as always the full PyTorch [documentation](https://pytorch.org/docs/stable/torch.html) is the ultimate resource.

*(Please insert cells below for your answers )*

In [11]:
data = np.array([1,2,3])
print(data.max())

datat = torch.tensor([1,2,3])
print(datat.max())

3
tensor(3)


In [12]:
print(np.ones(3))
print(np.zeros(3))
print(np.random.random(3))

print(torch.ones(3))
print(torch.zeros(3))
torch.rand(3)

[1. 1. 1.]
[0. 0. 0.]
[0.24186852 0.04924586 0.34970568]
tensor([1., 1., 1.])
tensor([0., 0., 0.])


tensor([0.2079, 0.0194, 0.4416])

In [13]:
data = np.array([1,2])
ones = np.ones(2)
print(data, ones)
data + ones

[1 2] [1. 1.]


array([2., 3.])

In [14]:
data = torch.tensor([1,2])
ones = torch.ones(2)
print(data, ones)
data + ones

tensor([1, 2]) tensor([1., 1.])


tensor([2., 3.])

In [15]:
# indexing

data = torch.tensor([1,2,3,4,5])

print(data)
print(data[0])
print(data[1])
print(data[1:2])
print(data[1:3])
print(data[1:])

tensor([1, 2, 3, 4, 5])
tensor(1)
tensor(2)
tensor([2])
tensor([2, 3])
tensor([2, 3, 4, 5])


In [16]:
print(data.max(), data.min(), data.sum())

tensor(5) tensor(1) tensor(15)


In [17]:
print(torch.Tensor.float(data).mean())
print(torch.Tensor.float(data).std())
print(data.prod())
print(1*2*3*4*5)

tensor(3.)
tensor(1.5811)
tensor(120)
120


In [18]:
print(torch.tensor([[1,2],[ 3,4]]))
print(torch.ones(3,2))
print(torch.zeros(3,2))
print(torch.rand(3,2))


tensor([[1, 2],
        [3, 4]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.4088, 0.6722],
        [0.5355, 0.9142],
        [0.9587, 0.6300]])


In [19]:
data = torch.tensor([[1,2], [3,4]])
print(data)
ones = torch.ones(2,2)
print(ones)

print(data + ones)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 3.],
        [4., 5.]])


In [20]:
data = torch.tensor([[1,2], [3,4], [5,6]])
print(data)
ones_row = torch.ones(1,2)
print(ones_row)

print(data + ones_row)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1., 1.]])
tensor([[2., 3.],
        [4., 5.],
        [6., 7.]])


In [21]:
data = torch.tensor([[1,2,3]])
pot = torch.tensor([[1,10], [100, 1000], [10000, 100000]])
print(data)
print(pot)
print(data.shape)
print(pot.shape)
print(torch.mm(data, pot))  # torch.dot only does 1D tensors...

tensor([[1, 2, 3]])
tensor([[     1,     10],
        [   100,   1000],
        [ 10000, 100000]])
torch.Size([1, 3])
torch.Size([3, 2])
tensor([[ 30201, 302010]])


In [22]:
data = torch.tensor([[1,2], [5,3], [4,6]])

print(data.min())
print(data.max())
print(data.max(axis=0))
print(data.max(axis=1))

tensor(1)
tensor(6)
torch.return_types.max(
values=tensor([5, 6]),
indices=tensor([1, 2]))
torch.return_types.max(
values=tensor([2, 5, 6]),
indices=tensor([1, 0, 1]))


In [23]:
data = torch.tensor([[1,2], [5,3], [4,6]])
print(data)
print(data.T)

tensor([[1, 2],
        [5, 3],
        [4, 6]])
tensor([[1, 5, 4],
        [2, 3, 6]])


In [24]:
data = torch.tensor([1,2,3,4,5,6])
print(data)
print(data.reshape(2,3))
print(data.reshape(3,2))

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [25]:
data = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])
print(data.shape)
print(data)

torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [26]:
predictions = torch.ones(3,1)
labels = torch.tensor([1,2,3]).reshape(3,1)
print(predictions)
print(labels)

tensor([[1.],
        [1.],
        [1.]])
tensor([[1],
        [2],
        [3]])


In [27]:
error = (1/3) * torch.sum(torch.square(predictions - labels))
print(error)
print(5/3)

tensor(1.6667)
1.6666666666666667


In [28]:
# For grader use only

G = [0]*2


# insert grade here  (maximum 10, subtract points if items are missing)
# G[1] = 

# please justify point subtractions

##  <font color = 'blue'> Question 2. Quadratic Regression

In the lecture we discussed a simple regression problem, where points are coming from the line $y = 2x + 1$, plus some noise.  For this question you are asked to: 

(i) Generate data points coming from a quadratic function: $ y = -x^2 + 3x +10 $, plus some noise. <br>
(ii) Modify the PyTorch model from the class in order for it to learn a quadratic function of the form $y = a x^2 + bx +c$. <br>
(iii) Train your model and report what values it computes. (Sanity check: These sould be close to -1, 3, 10)




In [29]:
# Data Generation
np.random.seed(42)
x = np.random.rand(100, 1)

y = -x**2 + 3 * x + 10 + .1 * np.random.randn(100, 1)

In [30]:
# Shuffles the indices
idx = np.arange(100)
np.random.shuffle(idx)

# Uses first 80 random indices for train
train_idx = idx[:80]
# Uses the remaining indices for validation
val_idx = idx[80:]

# Generates train and validation sets
x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

# Put the data in CPU (or GPU if available)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'using device {device}')

# Our data was in Numpy arrays, but we need to transform them into PyTorch's Tensors
# and then we send them to the chosen device
x_train_tensor = torch.from_numpy(x_train).float().to(device)
y_train_tensor = torch.from_numpy(y_train).float().to(device)

# Here we can see the difference - notice that .type() is more useful
# since it also tells us WHERE the tensor is (device)
print(type(x_train), type(x_train_tensor), x_train_tensor.type())

using device cuda
<class 'numpy.ndarray'> <class 'torch.Tensor'> torch.cuda.FloatTensor


In [31]:
# Create the THREE parameters. We require gradients and put them on the device at creation time.

torch.manual_seed(42)
a = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)
b = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)
c = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)
print(a, b, c)

tensor([0.1940], device='cuda:0', requires_grad=True) tensor([0.1391], device='cuda:0', requires_grad=True) tensor([-0.5187], device='cuda:0', requires_grad=True)


(ii) Modify the PyTorch model from the class in order for it to learn a quadratic function of the form $y = a x^2 + bx +c$. <br>
(iii) Train your model and report what values it computes. (Sanity check: These sould be close to -1, 3, 10)

In [32]:
lr = 1e-1
n_epochs = 10000 # CHANGING to 10K makes all the difference!!!

torch.manual_seed(42)
a = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)
b = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)
c = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)

for epoch in range(n_epochs):
    # yhat = a + b * x_train_tensor   # current predictions  b * x + a
    yhat = c + b * x_train_tensor + a*(x_train_tensor**2) 
    error = y_train_tensor - yhat   # error
    loss = (error ** 2).mean()      # compute loss

    
    # We just tell PyTorch to work its way BACKWARDS from the specified loss!
    loss.backward()
    # Let's check the computed gradients...
    #print(a.grad)
    #print(b.grad)
    #print(c.grad)
    
    # We need to use NO_GRAD to keep the update out of the gradient computation
    # Why is that? It boils down to the DYNAMIC GRAPH that PyTorch uses...
    with torch.no_grad():
        a -= lr * a.grad
        b -= lr * b.grad
        c -= lr * c.grad
    
    # PyTorch is "clingy" to its computed gradients, we need to tell it to let it go...
    a.grad.zero_()
    b.grad.zero_()
    c.grad.zero_()
    
print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')


a: tensor([-0.8058], device='cuda:0', requires_grad=True)
b: tensor([2.7796], device='cuda:0', requires_grad=True)
c: tensor([10.0514], device='cuda:0', requires_grad=True)


In [33]:
import torch.optim as optim
import torch.nn as nn
import math
class ManualQuadraticRegression(nn.Module):

    def __init__(self):
        super().__init__()
        # To make "a" and "b" real parameters of the model, we need to wrap them with nn.Parameter
        self.a = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        self.b = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        self.c = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        
    def forward(self, x):
        # Computes the outputs / predictions
        # ax^2 + bx + c
        return self.a * pow(x,2) + self.b * x + self.c

In [34]:
torch.manual_seed(42)

# Now we can create a model and send it at once to the device
model = ManualQuadraticRegression().to(device)

# We can also inspect its parameters using its state_dict
print(model.state_dict())

lr = 1e-1

# changing epochs from 1k to 10K made all the difference!!!!
n_epochs = 10000

loss_fn = nn.MSELoss(reduction='mean')
optimizer = optim.SGD(model.parameters(), lr=lr)

for epoch in range(n_epochs):
    
    # This sets the model in 'training' mode. We have to use this. 
    model.train()

    # No more manual prediction!
    # yhat = a + b * x_tensor
    yhat = model(x_train_tensor)
    
    loss = loss_fn(y_train_tensor, yhat)
    loss.backward()    
    optimizer.step()
    optimizer.zero_grad()
    
print(model.state_dict())

OrderedDict([('a', tensor([0.3367], device='cuda:0')), ('b', tensor([0.1288], device='cuda:0')), ('c', tensor([0.2345], device='cuda:0'))])
OrderedDict([('a', tensor([-0.8051], device='cuda:0')), ('b', tensor([2.7789], device='cuda:0')), ('c', tensor([10.0516], device='cuda:0'))])


In [35]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression


poly_reg=PolynomialFeatures(degree=2)
X_poly=poly_reg.fit_transform(x_train)
poly_reg.fit(X_poly,y_train)
lin_reg2=LinearRegression()
lin_reg2.fit(X_poly,y_train)
print(lin_reg2.intercept_, lin_reg2.coef_[0])

[10.05058536] [ 0.          2.78508306 -0.81125085]


In [36]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
model = make_pipeline(PolynomialFeatures(2), LinearRegression())

r = model.fit(x_train, y_train)

print(model.named_steps['linearregression'].intercept_)
print(model.named_steps['linearregression'].coef_)

[10.05058536]
[[ 0.          2.78508306 -0.81125085]]


In [37]:
# for grader use only

# insert grade here  
# part (i): 5, part(ii) 10, part (iii) 10

# G[2] = 
#
# please justify point subtractions