# Assignment 1


The solutions in this notebook are adapted from Susmita's work. 



## Preparation Steps

In [ ]:
# Import all necessary python packages
import numpy as np
import torch 



## <font color = 'blue'> Question 1. Basic Operations with Tensors </font>

Your taks for this question is to follow the NumPy  [**tutorial**](https://jalammar.github.io/visual-numpy/?fbclid=IwAR0tSntx5mj1aHteokRKrT4G6z77M3z0Quj40AQZ9mvKlhs2RTN3xXrc6Eo) we covered in the lecture, and 'mirror' each of the operations presented in the tutorial with tensors in PyTorch. 

You may find useful to consult this PyTorch introductory [tutorial](https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/), and as always the full PyTorch [documentation](https://pytorch.org/docs/stable/torch.html) is the ultimate resource.

*(Please insert cells below for your answers )*

### Creating Arrays

In [ ]:
arr = np.array([1,2,3])
torch_obj = torch.from_numpy(arr)
torch_obj

tensor([1, 2, 3])

In [ ]:
#Create array with ones
ones = torch.ones(3)
ones

tensor([1., 1., 1.])

In [ ]:
#Create array with zeros
zeros = torch.zeros(3)
zeros

tensor([0., 0., 0.])

In [ ]:
#Create array with random values
random = torch.randn(3)
random

tensor([0.9391, 0.5656, 0.1428])

### Array Arithmatic

In [ ]:
#Addition 
data = torch.from_numpy(np.array([1,2]))
ones = torch.ones(2)

data+ones

tensor([2., 3.])

In [ ]:
val = torch.add(data,ones)
print(val)

tensor([2., 3.])


In [ ]:
#Subtraction
data = torch.from_numpy(np.array([1,2]))
ones = torch.ones(2)

data-ones

tensor([0., 1.])

In [ ]:
val = torch.sub(data,ones)
print(val)

tensor([0., 1.])


In [ ]:
#Multiplication 
data = torch.from_numpy(np.array([1,2]))
data*data

tensor([1, 4])

In [ ]:
val = torch.mul(data,data)
print(val)

tensor([1, 4])


In [ ]:
#Division
data = torch.from_numpy(np.array([1,2]))
data/data

tensor([1., 1.])

In [ ]:
val = torch.div(data,data)
print(val)

tensor([1., 1.])


In [ ]:
#Multiplication with scalar values
data = torch.from_numpy(np.array([1,2]))
data*1.6

tensor([1.6000, 3.2000])

### Array Indexing

In [ ]:
torch_obj[0]

tensor(1)

In [ ]:
torch_obj[1]

tensor(2)

In [ ]:
torch_obj[0:2]

tensor([1, 2])

In [ ]:
torch_obj[1:]

tensor([2, 3])

### Aggregation

In [ ]:
torch_obj.max()

tensor(3)

In [ ]:
torch_obj.min()

tensor(1)

In [ ]:
torch_obj.sum()

tensor(6)

### Creating Matrices

In [ ]:
#Creating matrix
data = torch.from_numpy(np.array([[1,2],[3,4]]))
data

tensor([[1, 2],
        [3, 4]])

In [ ]:
#Create array with ones
ones = torch.ones((3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
#Create array with zeros
zeros = torch.zeros((3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
#Create array with random values
random = torch.randn((3,2))
random

tensor([[-1.5406, -1.0072],
        [-0.4095,  0.4484],
        [ 0.3014, -1.5049]])

### Matrix Arithmatic

In [ ]:
#Addition 
ones = torch.ones((2,2))
data+ones

tensor([[2., 3.],
        [4., 5.]])

In [ ]:
val = torch.add(data,ones)
val

tensor([[2., 3.],
        [4., 5.]])

In [ ]:
data = torch.from_numpy(np.array([[1,2],[3,4],[5,6]]))
ones = torch.ones((1,2))
data+ones


tensor([[2., 3.],
        [4., 5.],
        [6., 7.]])

In [ ]:
val = torch.add(data,ones)
val

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]])

In [ ]:
#Dot product

data = torch.from_numpy(np.array([1,2,3]))
powers_of_ten = torch.from_numpy(np.array([[1,10],[100,1000],[10000,100000]]))

val = data.matmul(powers_of_ten)
val

tensor([ 30201, 302010])

### Matrix Indexing

In [ ]:
data = torch.from_numpy(np.array([[1,2],[3,4],[5,6]]))
data

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
data[0,1]

tensor(2)

In [ ]:
data[1:3]

tensor([[3, 4],
        [5, 6]])

In [ ]:
data[0:2,0]

tensor([1, 3])

### Matrix Aggregation

In [ ]:
data.max()

tensor(6)

In [ ]:
data.min()

tensor(1)

In [ ]:
data.sum()

tensor(21)

In [ ]:
data = torch.from_numpy(np.array([[1,2],[5,3],[4,6]]))
data.max(axis=0)

torch.return_types.max(values=tensor([5, 6]), indices=tensor([1, 2]))

In [ ]:
data.max(axis=1)

torch.return_types.max(values=tensor([2, 5, 6]), indices=tensor([1, 0, 1]))

### Transposing and Reshaping 

In [ ]:
data = torch.from_numpy(np.array([[1,2],[3,4],[5,6]]))
data.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
data = torch.from_numpy(np.array([1,2,3,4,5,6]))
data

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
data.reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
data.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### More Dimensions 

In [ ]:
data = torch.from_numpy(np.array([[[1,2],[3,4]],[[5,6],[7,8]]]))
data

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
ones = torch.ones((4,3,2))
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
zeros = torch.zeros((4,3,2))
zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
random = torch.randn((4,3,2))
random

tensor([[[-0.8122,  0.6558],
         [ 1.9728,  0.3739],
         [-0.3677, -1.7055]],

        [[-0.4628, -0.4727],
         [ 0.2523,  0.8521],
         [-0.3699,  1.0112]],

        [[-0.8304,  1.0936],
         [-0.6869,  0.3505],
         [-1.3919, -0.3991]],

        [[-1.0848, -0.1577],
         [-0.4066, -0.2527],
         [-0.0327, -0.5594]]])

### Formulas

In [ ]:
predictions = torch.ones(3)
labels = torch.from_numpy(np.array([1,2,3]))
error = (1/3)*torch.sum(torch.square(predictions-labels))
error

tensor(1.6667)

In [ ]:
# For grader use only

G = [0]*2


# insert grade here  (maximum 10, subtract points if items are missing)
G[0] = 10

# please justify point subtractions

##  <font color = 'blue'> Question 2. Quadratic Regression

In the lecture we discussed a simple regression problem, where points are coming from the line $y = 2x + 1$, plus some noise.  For this question you are asked to: 

(i) Generate data points coming from a quadratic function: $ y = -x^2 + 3x +10 $, plus some noise. <br>
(ii) Modify the PyTorch model from the class in order for it to learn a quadratic function of the form $y = a x^2 + bx +c$. <br>
(iii) Train your model and report what values it computes. (Sanity check: These sould be close to -1, 3, 10)




In [7]:
import torch.optim as optim
import torch.nn as nn
import numpy as np
import torch

In [4]:
#(i) Generate data points coming from a quadratic function:  𝑦=−𝑥**2+3𝑥+10 , plus some noise.

np.random.seed(42)
x = np.random.rand(100, 1)
y = -x**2 + 3 * x + 10 + .1 * np.random.randn(100, 1)

In [5]:
# Shuffles the indices
idx = np.arange(100)
np.random.shuffle(idx)

# Uses first 80 random indices for train
train_idx = idx[:80]
# Uses the remaining indices for validation
val_idx = idx[80:]

# Generates train and validation sets
x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# the data points needs to be converted from numpy array
# to Tensor objects
x_train_tensor = torch.from_numpy(x_train).float().to(device)
y_train_tensor = torch.from_numpy(y_train).float().to(device)

In [9]:
#(ii) Modify the PyTorch model from the class in order for it to learn a quadratic function of the form  𝑦=𝑎𝑥**2+𝑏𝑥+𝑐 .

class QuadraticRegression(nn.Module):
    def __init__(self):
        super().__init__()
        # To make "a","b" and "c" real parameters of the model, we need to wrap them with nn.Parameter
        self.a = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        self.b = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        self.c = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

    def forward(self, x):
        # Computes the outputs / predictions based on the quadratic functions
        return self.a * x**2 + self.b * x + self.c

In [17]:
#(iii) Train your model and report what values it computes.

torch.manual_seed(42)

# Creating a model and send it at once to the device
model = QuadraticRegression().to(device)

#define learning rate
lr = 1e-1
n_epochs = 20000

#define loss function and optimizer
loss_fn = nn.MSELoss(reduction='mean')
optimizer = optim.SGD(model.parameters(), lr=lr)

for epoch in range(n_epochs):
    # This sets the model in 'training' mode. 
    model.train()
    yhat = model(x_train_tensor)
    
    loss = loss_fn(y_train_tensor, yhat)
    loss.backward()    
    optimizer.step()
    optimizer.zero_grad()

In [18]:
print(model.state_dict())

OrderedDict([('a', tensor([-0.8111], device='cuda:0')), ('b', tensor([2.7849], device='cuda:0')), ('c', tensor([10.0506], device='cuda:0'))])
